name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  Git-Checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests=false
        
  Upload-Artifcat:
    runs-on: ubuntu-latest
    needs: Git-Checkout

    steps:
      - name: Git Checkout code
        uses: actions/checkout@v4

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
